services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      TYPE: "PAPER"
      MOTD: "server dos pais chatos"      
      ENABLE_WHITELIST: "true"
      WHITELIST: "MrFleck, Aerseth, uillismiti, Molina2612, DominusXXI"
      OPS: "MrFleck"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "NosSomosOsPaisChatos@2025"
    volumes:
      - ./data:/data
      - ./world:/data/world
    restart: unless-stopped
